apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: net-backend-service-github
  title: .NET backend service for GitHub
  description: Creates a .NET backend service in GitHub
  labels:
    example.com/custom: custom_label_value
spec:
  owner: Enablement
  type: service
  parameters:
    - title: Fill in some variables
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component. Will be used as repository name.
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: ${{ steps.publish.output.remoteUrl }}
    entityRef: ${{ steps.register.output.entityRef }}
